# Normalization

In [1]:
#array
import numpy as np
x = [13, 15, 16, 16, 19, 20, 20, 21, 22, 22, 25, 25, 25, 25, 30, 33, 33, 35, 35, 35, 35, 36, 40, 45, 46, 52, 70]
x = np.array(x)
# reshape to prepare for scale
x = np.reshape(x,(-1,1))
x

array([[13],
       [15],
       [16],
       [16],
       [19],
       [20],
       [20],
       [21],
       [22],
       [22],
       [25],
       [25],
       [25],
       [25],
       [30],
       [33],
       [33],
       [35],
       [35],
       [35],
       [35],
       [36],
       [40],
       [45],
       [46],
       [52],
       [70]])

### Min-max normalization
z_i  =  (x_i-min⁡(x))/(max⁡(x)-min⁡(x) )

In [2]:
from sklearn.preprocessing import MinMaxScaler
minMaxScaler = MinMaxScaler(feature_range=(0,1))
minMaxScaler.fit(x)
minMaxScaler.transform(x)

c:\python34\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.        ],
       [0.03508772],
       [0.05263158],
       [0.05263158],
       [0.10526316],
       [0.12280702],
       [0.12280702],
       [0.14035088],
       [0.15789474],
       [0.15789474],
       [0.21052632],
       [0.21052632],
       [0.21052632],
       [0.21052632],
       [0.29824561],
       [0.35087719],
       [0.35087719],
       [0.38596491],
       [0.38596491],
       [0.38596491],
       [0.38596491],
       [0.40350877],
       [0.47368421],
       [0.56140351],
       [0.57894737],
       [0.68421053],
       [1.        ]])

### Z-score normalization
z_i  =  (x_i- mean)/std

In [3]:
from sklearn.preprocessing import StandardScaler
meanX = np.mean(x)
stdX = np.std(x)
ZscoreScaler = StandardScaler()
ZscoreScaler.fit(x)
print (ZscoreScaler.transform(x))
print (np.std(ZscoreScaler.transform(x)))
stdX

[[-1.33564599e+00]
 [-1.17816807e+00]
 [-1.09942912e+00]
 [-1.09942912e+00]
 [-8.63212252e-01]
 [-7.84473297e-01]
 [-7.84473297e-01]
 [-7.05734341e-01]
 [-6.26995386e-01]
 [-6.26995386e-01]
 [-3.90778520e-01]
 [-3.90778520e-01]
 [-3.90778520e-01]
 [-3.90778520e-01]
 [ 2.91625761e-03]
 [ 2.39133124e-01]
 [ 2.39133124e-01]
 [ 3.96611035e-01]
 [ 3.96611035e-01]
 [ 3.96611035e-01]
 [ 3.96611035e-01]
 [ 4.75349990e-01]
 [ 7.90305812e-01]
 [ 1.18400059e+00]
 [ 1.26273954e+00]
 [ 1.73517328e+00]
 [ 3.15247448e+00]]
1.0


c:\python34\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


12.700193878606099